local icons = {
	plugins = {
		cmd = " ",
		debug = " ",
		event = " ",
		keys = "󰌆 ",
		loaded = "",
		not_loaded = "",
		plugin = "󰏔 ",
		runtime = " ",
		source = "󰘬 ",
		start = " ",
	},
	debugger = {
		play = "",
		pause = "",
		step_into = "󰆹",
		step_over = "",
		step_out = "",
		step_back = "",
		run_last = "",
		terminate = "",
		disconnect = "",
	},
	outline = {
		Class = " 󰠱",
		Function = " 󰊕",
		Method = " 󰖷",
		Interface = " ",
		Struct = " ",
		Array = " 󰅨",
		Constructor = " ",
		Enum = " ",
		Module = " 󰐱",
	},
	completion = {
		Array = "󰅨",
		Boolean = "",
		Class = "󰠱",
		Color = "󰏘",
		Constant = "󰏿",
		Constructor = "",
		Enum = "",
		EnumMember = "",
		Event = "",
		File = "",
		Folder = "",
		Function = "󰊕",
		Interface = "",
		Key = "󰌆",
		Keyword = "󰌆",
		Method = "󰖷",
		Module = "󰐱",
		Null = "",
		Number = "",
		Package = "󰏔",
		Property = "󰖷",
		Snippet = "",
		Struct = "",
		Text = "󰉿",
		Unit = "",
	},
	manager = {
		package_installed = "",
		package_pending = "",
		package_uninstalled = "",
	},
	notifications = {
		TRACE = "",
		DEBUG = "",
		INFO = "",
		WARN = "",
		ERROR = "",
	},
	explorer = {
		folder = {
			arrow_closed = " ",
			arrow_open = " ",
			default = "",
			open = "",
			empty = "",
			empty_open = "",
			symlink = "",
			symlink_open = "",
		},
		git = {
			staged = "",
			unstaged = "",
			unmerged = "",
			deleted = "",
			ignored = "",
			renamed = "",
			untracked = "",
		},
	},
}

return icons
